version: "3"

services:
  app:
    build: .
    command: npm start
    ports:
      - "3001:3001"
    volumes:
      - .:/usr/app
    depends_on:
      - "mongo"
    networks:
      - backend

  mongo:
    container_name: "mongo-node"
    platform: linux/amd64
    image: mongo:4.4.14
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
    networks:
      - backend

networks:
  backend:
    driver: bridge