version: "3"

services:
  app:
    build: .
    command: npm start
    ports:
      - "3003:3003"
    volumes:
      - .:/usr/app
    networks:
      - backend

networks:
  backend:
    driver: bridge